<h2>Examenes/AltaExamenes</h2>

<table>
    <tbody>
        <tr>
            <th>Enunciado</th>
            <th>Tématica</th>
        </tr>
    </tbody>
</table>
<table>
    <tbody>
        <tr>
            <th>ID</th>
            <th>Enunciado</th>
            <th>Temática</th>
        </tr>
    </tbody>
</table>